server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.100.92:13306/db_meta?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cclucky
    initial-size: 20
    max-idle: 60
    max-wait: 10000
    min-idle: 10
    max-active: 200
  redis:
    database: 2
    host: 192.168.100.92
    port: 16379
    password: cclucky
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
      connect-timeout: 30000ms
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        ddl-auto:
          auto: create
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use-new-id-generator-mappings: false
